<?php
/**
 * DataApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KizeoFormsApi\Client\Test\Api;

use \KizeoFormsApi\Client\Configuration;
use \KizeoFormsApi\Client\ApiException;
use \KizeoFormsApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DataApiTest Class Doc Comment
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for formsFormIdDataAdvancedPost
     *
     * Get List of filtered data of a form (with advanced filtering options).
     *
     */
    public function testFormsFormIdDataAdvancedPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataAllGet
     *
     * Get the list of all data of a form.
     *
     */
    public function testFormsFormIdDataAllGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataDataIdDeleteDelete
     *
     * Delete a data.
     *
     */
    public function testFormsFormIdDataDataIdDeleteDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataDataIdGet
     *
     * Get data of a form.
     *
     */
    public function testFormsFormIdDataDataIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataGet
     *
     * Get the list of all data of a form (not read).
     *
     */
    public function testFormsFormIdDataGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataReadnewGet
     *
     * Get content of unread data.
     *
     */
    public function testFormsFormIdDataReadnewGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataSearchPost
     *
     * Get List of filtered data of a form.
     *
     */
    public function testFormsFormIdDataSearchPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdMarkasreadPost
     *
     * Set list of data of a form to read.
     *
     */
    public function testFormsFormIdMarkasreadPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdMarkasunreadPost
     *
     * Set list of data of form to unread.
     *
     */
    public function testFormsFormIdMarkasunreadPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdPushDataIdPost
     *
     * Send push with data.
     *
     */
    public function testFormsFormIdPushDataIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdPushPost
     *
     * Send push with data.
     *
     */
    public function testFormsFormIdPushPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsPushInboxGet
     *
     * Receive new pushed data.
     *
     */
    public function testFormsPushInboxGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
