<?php
/**
 * ExportsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KizeoFormsApi\Client\Test\Api;

use \KizeoFormsApi\Client\Configuration;
use \KizeoFormsApi\Client\ApiException;
use \KizeoFormsApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for formsFormIdDataDataIdExportsExportIdGet
     *
     * Export data.
     *
     */
    public function testFormsFormIdDataDataIdExportsExportIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataDataIdExportsExportIdPdfGet
     *
     * Export data (PDF).
     *
     */
    public function testFormsFormIdDataDataIdExportsExportIdPdfGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataDataIdFormPicturesMediaNameGet
     *
     * Get one fixed image of a form.
     *
     */
    public function testFormsFormIdDataDataIdFormPicturesMediaNameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataDataIdMediasMediaNameGet
     *
     * Get one image of a form.
     *
     */
    public function testFormsFormIdDataDataIdMediasMediaNameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataDataIdPdfGet
     *
     * Get PDF data of a form.
     *
     */
    public function testFormsFormIdDataDataIdPdfGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataMultipleCsvCustomPost
     *
     * Get custom CSV data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleCsvCustomPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataMultipleCsvPost
     *
     * Get CSV data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleCsvPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataMultipleExcelCustomPost
     *
     * Get custom Excel list data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleExcelCustomPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdDataMultipleExcelPost
     *
     * Get Excel list data (multiple) of a form.
     *
     */
    public function testFormsFormIdDataMultipleExcelPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdExportsGet
     *
     * Get list of Word and Excel exports.
     *
     */
    public function testFormsFormIdExportsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for formsFormIdMultipleDataExportsExportIdPdfPost
     *
     * Export data (multiple / PDF).
     *
     */
    public function testFormsFormIdMultipleDataExportsExportIdPdfPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
