<?php
/**
 * GroupsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KizeoFormsApi\Client\Test\Api;

use \KizeoFormsApi\Client\Configuration;
use \KizeoFormsApi\Client\ApiException;
use \KizeoFormsApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for groupGroupIdDelete
     *
     * Delete a group.
     *
     */
    public function testGroupGroupIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdGet
     *
     * Get a group.
     *
     */
    public function testGroupGroupIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdLeaderLeaderIdDelete
     *
     * Remove a leader from a specific group.
     *
     */
    public function testGroupGroupIdLeaderLeaderIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdLeaderLeaderIdPost
     *
     * Add a leader into a specific group.
     *
     */
    public function testGroupGroupIdLeaderLeaderIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdLeadersGet
     *
     * Get all groups' leaders of a specific group.
     *
     */
    public function testGroupGroupIdLeadersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdLeadersPost
     *
     * Add several leaders into a group.
     *
     */
    public function testGroupGroupIdLeadersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdPut
     *
     * Update a group.
     *
     */
    public function testGroupGroupIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdUserUserIdDelete
     *
     * Remove an user from a specific group.
     *
     */
    public function testGroupGroupIdUserUserIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdUserUserIdPost
     *
     * Add an user into a specific group.
     *
     */
    public function testGroupGroupIdUserUserIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdUsersGet
     *
     * Get all users of a specific group.
     *
     */
    public function testGroupGroupIdUsersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupGroupIdUsersPost
     *
     * Add several users into a group.
     *
     */
    public function testGroupGroupIdUsersPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupPost
     *
     * Create a new group.
     *
     */
    public function testGroupPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupsGet
     *
     * Get all groups.
     *
     */
    public function testGroupsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for groupsOrderedGet
     *
     * Get all groups ordered.
     *
     */
    public function testGroupsOrderedGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
