<?php
/**
 * ListsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Kizeo REST
 *
 * This is a Swagger generated doc for Kizeo REST API 3. You can find additionnal documentation here : [Online documentation](/doc).
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@kizeo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace KizeoFormsApi\Client\Test\Api;

use \KizeoFormsApi\Client\Configuration;
use \KizeoFormsApi\Client\ApiException;
use \KizeoFormsApi\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  KizeoFormsApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ListsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for listsGet
     *
     * Get External Lists.
     *
     */
    public function testListsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listsListIdCompleteGet
     *
     * Get External List Definition (Without taking in account filters).
     *
     */
    public function testListsListIdCompleteGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listsListIdGet
     *
     * Get External List Definition.
     *
     */
    public function testListsListIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listsListIdPut
     *
     * Update External List Definition.
     *
     */
    public function testListsListIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
